# Created by SergioK12, like-engels (2024-11-29, Nicaragua)
# Copyright © 2024. All rights reserved.
services:
  postgres:
    image: postgres:17.2
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_USER=postgrecito
      - POSTGRES_DB=pinol
  nginx: 
    image: nginx:1.27.3
    ports:
      - 8080:80
      - 443:443

  frontend:
    build:
      context: ./pinol-frontend
    ports:
        - 3000:3000
    depends_on:
      - postgres
      - nginx