name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install root dependencies
        run: npm ci

      - name: Install frontend dependencies
        working-directory: pinol-frontend
        run: npm ci

      - name: Start Next.js app
        working-directory: pinol-frontend
        run: |
          npm run dev &
          echo $! > nextjs.pid
          echo "Waiting for Next.js to start..."
          npx wait-on http://localhost:3000

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Stop Next.js app
        if: ${{ always() }}
        working-directory: pinol-frontend
        run: |
          kill $(cat nextjs.pid)
